const canvas = document.getElementById("canvas1");
const ctx = canvas.getContext("2d");
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;
const collisionCanvas = document.getElementById("collisionCanvas");
const collisionCtx = collisionCanvas.getContext("2d");
collisionCanvas.width = window.innerWidth;
collisionCanvas.height = window.innerHeight;
let score = 0;
ctx.font = "50px Impact";

// Counter
let timeToNextRaven = 0;
// Milliseconds per raven release
let ravenInterval = 500;
// Keeps track of previous time
let lastTime = 0;

let ravens = [];
class Raven {
  constructor() {
    this.spriteWidth = 271;
    this.spriteHeight = 194;
    this.sizeModifier = Math.random() * 0.6 + 0.4;
    this.width = this.spriteWidth * this.sizeModifier;
    this.height = this.spriteHeight * this.sizeModifier;
    this.x = canvas.width;
    this.y = Math.random() * (canvas.height - this.height);
    // Horizontal speed (basically)
    this.directionX = Math.random() * 5 + 3;
    // Up and down movement between -2.5 and 2.5
    this.directionY = Math.random() * 5 - 2.5;
    this.markedForDeletion = false;
    this.image = new Image();
    this.image.src = "./assets/raven.png";
    this.frame = 0;
    this.maxFrame = 4;
    this.timeSinceFlap = 0;
    // Flap speed determined, in part, by horizontal movement speed
    this.flapInterval = 400 / this.directionX;
    // Random color values for hit boxes on the second canvas
    this.randomColors = [
      Math.floor(Math.random() * 255),
      Math.floor(Math.random() * 255),
      Math.floor(Math.random() * 255),
    ];
    this.color =
      "rgb(" +
      this.randomColors[0] +
      "," +
      this.randomColors[1] +
      "," +
      +this.randomColors[2] +
      ")";
  }
  update(deltatime) {
    if (this.y < 0 || this.y > canvas.height - this.height) {
      this.directionY = this.directionY * -1;
    }
    this.x -= this.directionX;
    this.y += this.directionY;
    if (this.x < 0 - this.width) this.markedForDeletion = true;
    this.timeSinceFlap += deltatime;
    if (this.timeSinceFlap > this.flapInterval) {
      if (this.frame > this.maxFrame) this.frame = 0;
      else this.frame++;
      this.timeSinceFlap = 0;
    }
  }
  draw() {
    ctx.fillStyle = this.color;
    ctx.fillRect(this.x, this.y, this.width, this.height);
    ctx.drawImage(
      this.image,
      this.frame * this.spriteWidth,
      0,
      this.spriteWidth,
      this.spriteHeight,
      this.x,
      this.y,
      this.width,
      this.height
    );
  }
}

function drawScore() {
  // The two versions provide a shadow effect
  ctx.fillStyle = "black";
  ctx.fillText("Score: " + score, 50, 75);
  ctx.fillStyle = "white";
  ctx.fillText("Score: " + score, 55, 80);
}

window.addEventListener("click", (e) => {
  // Gets data of the pixel clicked (x, y, width, height)
  const detectPixelColor = ctx.getImageData(e.x, e.y, 1, 1);
  console.log(detectPixelColor);
});

// Timestamp is automatically generated by JavaScript
function animate(timestamp) {
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  let deltatime = timestamp - lastTime;
  lastTime = timestamp;
  timeToNextRaven += deltatime;
  // Creates a new raven and resets the count
  if (timeToNextRaven > ravenInterval) {
    ravens.push(new Raven());
    timeToNextRaven = 0;
  }
  // Before ravens to be behind them
  drawScore();
  // Array literal is used by only having an array
  [...ravens].forEach((raven) => raven.update(deltatime));
  [...ravens].forEach((raven) => raven.draw());
  // Only keeps ravens that are not marked for deletion
  ravens = ravens.filter((raven) => raven.markedForDeletion === false);
  requestAnimationFrame(animate);
}
// Without a starting timestamp value, it is NaN
animate(0);
